IIF(COMPONENT_ROOT != "TAG",
    (IIF(COMPONENT_ROOT != "X",
         (IIF(COMPONENT_ROOT != "Q",
              REPLACE(COMPONENT_ROOT, "F", "Q") + STRZ(VAL(COMPONENT_ORDERNO), 2, 0),
              "F" + STRZ(VAL(COMPONENT_ORDERNO), 2, 0))),

         "" + STRZ(VAL(COMPONENT_ORDERNO), 1, 0))),

    "X" + STRZ(VAL(COMPONENT_ORDERNO), 1, 0))


IIF(COMPONENT_ROOT != "J",
    (IIF(COMPONENT_ROOT != "X",
         (IIF(COMPONENT_ROOT != "Q",
              REPLACE(COMPONENT_ROOT, "F", "Q") + STRZ(VAL(COMPONENT_ORDERNO), 2, 0),

              "F" + STRZ(VAL(COMPONENT_ORDERNO), 2, 0))),

         "" + STRZ(VAL(COMPONENT_ORDERNO), 2, 0))),

    "" + STRZ(VAL(COMPONENT_ORDERNO), 2, 0))